language: node_js
node_js:
  "node"
cache:
  directories:
    "node_modules"
script:
  npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GH_TOKEN
  on:
    branch: master